export interface Violation {
  id: string;
  query: string;
  severity: ViolationSeverity;
  description?: string; // For reporting or tooltips
}

export const violations: Violation[] = [
  // HIGH RISK (Critical Food Safety / Legal)
  { id: 'hot-held-temp', query: "Are hot held food temperatures at or above required levels of 135?", severity: 'high' },
  { id: 'cold-food-over-41', query: "Is there cold food over 41°F or hot food below 140°F on any food surfaces?", severity: 'high' },
  { id: 'cold-food-over-60', query: "Is there cold food over 60°F or hot food below 120°F on any food surfaces?", severity: 'high' },
  { id: 'improper-label-cambro', query: "Is food in plastic Cambro pans correct labeled with day and label is not more than 3 days old", severity: 'high' },
  { id: 'hand-sink-hot-water', query: "Is hot water at each hand sink reaching required temperature of 105 Farenheit?", severity: 'high' },
  { id: 'handwashing-sinks-working', query: "Are all associate handwashing sinks working and accessible?", severity: 'high' },
  { id: 'sink-hot-water', query: "Is hot water available at each sink?", severity: 'high' },
  { id: 'handwashing-moments', query: "Are associates actively washing hands at required moments?", severity: 'high' },
  { id: 'eating-kitchen', query: "Are associates drinking or eating in the kitchen?", severity: 'high' },
  { id: 'gum-tobacco', query: "Are associates chewing gum or using tobacco while working?", severity: 'high' },
  { id: 'wash-after-restroom', query: "Are associates washing hands after using restrooms or touching face/eyes/mouth?", severity: 'high' },
  { id: 'cross-contamination', query: "Is there cross contamination from raw/ready-to-eat or processed/vegetable items?", severity: 'high' },
  { id: 'sewage-backup', query: "Are there any sewage backup or restrooms not working?", severity: 'high' },
  { id: 'flies-cockroaches', query: "Are flies or cockroaches present in the facility?", severity: 'high' },
  { id: 'improper-thawing', query: "Is there any improper thawing (do not use standing water, leave at room temp, or thaw in running water)?", severity: 'high' },
  { id: 'leftover-food-discard', query: "Is all leftover food discarded after 7 days?", severity: 'high' },
  { id: 'expired-unlabeled-food', query: "Is there any expired or unlabeled food in the store?", severity: 'high' },
  { id: 'walk-in-temp', query: "Is walk-in cooler/freezer functioning and at the correct temperature walkin cooler at less than 42 degrees f and freezer lower than 0 degrees f?", severity: 'high' },
  { id: 'handwashing-sink-use', query: "Is the designated handwashing sink used only for washing hands?", severity: 'high' },
  { id: 'all-handwashing-sink-use', query: "Are all handwashing sinks used only for handwashing?", severity: 'high' },
  { id: 'chemical-storage', query: "Are all chemical and cleaning agents stored away from food and prep areas?", severity: 'high' },
  { id: 'produce-storage', query: "Is produce in the walk-in cooler/freezer stored above ready-to-eat foods?", severity: 'high' },
  { id: 'scoop-handle', query: "Is there any scoop handle inside of the food on induction or steam table?", severity: 'high' },
  { id: 'two-ingredients-same-container', query: "Are two or more ingredients stored together in the same container?", severity: 'high' },
  { id: 'about-to-touch-face', query: "Is any employee about to touch their face, eyes, or mouth?", severity: 'high' },
  { id: 'not-washing-hands-break', query: "Is anyone not washing hands after returning from break or restroom?", severity: 'high' },
  { id: 'dirty-gloves', query: "Are any gloves looking dirty or torn?", severity: 'high' },
  { id: 'no-hair-restraint', query: "Is anyone not wearing a hair restraint or cap, but near food prep?", severity: 'high' },
  { id: 'sanitize-towel-misuse', query: "Are surfaces being wiped with dry towels instead of sanitizer towels?", severity: 'high' },
  { id: 'unlabeled-home-food', query: "Is all homemade food labeled with date and name?", severity: 'high' },

  // MEDIUM RISK (Operational / Food Quality / Cleanliness)
  { id: 'steam-rice-unit', query: "Is steam rice unit clean and functioning?", severity: 'medium' },
  { id: 'storage-organized', query: "Is all food and chemical storage organized properly?", severity: 'medium' },
  { id: 'prep-dish-sinks', query: "Are all prep and dish area sinks working?", severity: 'medium' },
  { id: 'lighting-shielded', query: "Are all lighting sources in the store properly shielded and functioning?", severity: 'medium' },
  { id: 'standing-water', query: "Are there any standing sources of water in the store?", severity: 'medium' },
  { id: 'mop-area', query: "Is the mop area left clean and mop sink functioning?", severity: 'medium' },
  { id: 'sanitizer-strips', query: "Are sanitizer strips available?", severity: 'medium' },
  { id: 'clean-pans', query: "Are all clean pans, lids, or plastic containers free of debris or grease?", severity: 'medium' },
  { id: 'pans-upside-down', query: "Are all pans and containers stored upside down?", severity: 'medium' },
  { id: 'drains-clean', query: "Are all drains clean?", severity: 'medium' },
  { id: 'surfaces-clean', query: "Are all surfaces clean including counters, doors, shelves, fan guards, and gaskets?", severity: 'medium' },
  { id: 'floor-under-equip', query: "Is the floor under cooking range and service table scales clean?", severity: 'medium' },
  { id: 'deep-fryer-clean', query: "Is the deep fryer free of build-up grease or debris?", severity: 'medium' },
  { id: 'personal-items-locker', query: "Are personal items kept inside lockers?", severity: 'medium' },
  { id: 'drink-policy', query: "Are associates drinks using a cup with lid and straw and placed on designated shelf?", severity: 'medium' },
  { id: 'homemade-food-workarea', query: "Are home-made food or drinks present in the work area?", severity: 'medium' },
  { id: 'wet-sanitizing-towels', query: "Are wet sanitizing towels stored in sanitizing solution?", severity: 'medium' },
  { id: 'proper-food-storage', query: "Are only proper food items stored in designated areas?", severity: 'medium' },
  { id: 'sinks-working', query: "Are all sinks in working condition?", severity: 'medium' },
  { id: 'sinks-purpose', query: "Are all sinks used only for their intended purpose?", severity: 'medium' },
  { id: 'meat-scales', query: "Are all meat scales clean and functioning?", severity: 'medium' },
  { id: 'personal-items-prep', query: "Are personal items not left out in prep area?", severity: 'medium' },
  { id: 'utensils-proper-storage', query: "Are all clean utensils stored in proper containers?", severity: 'medium' },
  { id: 'utensils-not-floor', query: "Are all utensils clean and not stored on the floor?", severity: 'medium' },
  { id: 'cutting-boards-clear', query: "Are cutting boards and sinks not blocked by anything?", severity: 'medium' },
  { id: 'damage-equip-facility', query: "Is there any damage to equipment or facilities?", severity: 'medium' },
  { id: 'gasket-damage', query: "Is there any torn, damaged, or organic build-up in gaskets?", severity: 'medium' },
  { id: 'towel-cooking-position', query: "Is there a clean and dry towel on each kitchen cooking position?", severity: 'medium' },
  { id: 'utensils-out-surfaces', query: "Are there any utensils or tools left out on surfaces instead of being put away?", severity: 'medium' },
  { id: 'open-food-packages', query: "Are there any open food packages that should be sealed?", severity: 'medium' },
  { id: 'walk-in-doors', query: "Are walk-in cooler/freezer doors not closed all the way?", severity: 'medium' },
  { id: 'clutter-prep', query: "Is there clutter or excess items on prep tables?", severity: 'medium' },
  { id: 'sinks-getting-cluttered', query: "Are any sinks starting to get cluttered with dishes or containers?", severity: 'medium' },
  { id: 'aprons-not-worn', query: "Are aprons not being worn in food prep areas?", severity: 'medium' },
  { id: 'using-phone-prep', query: "Is anyone using a personal phone in a food prep area?", severity: 'medium' },
  { id: 'music-tv-volume', query: "Is the music or TV volume high enough to be a distraction?", severity: 'medium' },
  { id: 'labels-peeling', query: "Are food labels starting to peel or become illegible?", severity: 'medium' },

  // LOW RISK (Minor Cleanliness / Stock / Comfort)
  { id: 'short-gloves-towels', query: "Is there a shortage of gloves, towels, or sanitizer at work stations?", severity: 'low' },
  { id: 'soap-towel-dispensers', query: "Are any soap or paper towel dispensers nearly empty?", severity: 'low' },
  { id: 'trash-bins-full', query: "Are trash bins nearly full and need to be taken out soon?", severity: 'low' },
  { id: 'floor-clean-dry', query: "Is the floor clean and dry, or are there small spills that could be cleaned up?", severity: 'low' },
  { id: 'restrooms-stocked', query: "Are restrooms adequately stocked and cleaned on schedule?", severity: 'low' },
  { id: 'non-designated-eating', query: "Is anyone preparing to eat or drink in a non-designated area?", severity: 'low' },
];

export type ViolationSeverity = 'high' | 'medium' | 'low';
